### ISSUE TITLE
外部サイトのリンク踏んだ時に別タブで開くようにしてほしい

### ISSUE THREAD

**Issue by tenchi0815** [tetsu26/Calliope-seminar#20]
よくわからんけどIssue使ってみた

**Comment by tetsu26** [comment]
うるせ〜〜！！！！！
知らね〜〜〜〜！！！！
　　　　🤴
　　👊╋━━━━
　　　　　𝑭𝑰𝑵𝑨𝑳 𝑭𝑨𝑵𝑻
                                    𝑨𝑺𝒀

**Comment by tenchi0815** [comment]
草

**Comment by tetsu26** [comment]
https://twitter.com/nmnoy/status/904540273358684164
